spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quotes
    generate-unique-name: false
    name: quotes
    username: testuser
    password: testpass

  h2:
    console:
      enabled: on
      settings:
        web-allow-others: true


server:
  port: 8080
#  ssl:
#    key-store: classpath:abbtestkeystore.p12
#    key-store-password: testpass
#    keyStoreType: PKCS12
#    keyAlias: abbtestkey
#    enabled: true
